package trycatch;

public class TryCatchDay2 {

	public static void main(String[] args) {

		System.out.println("Begining");

		try {
			throw new ArithmeticException();

		} catch (NullPointerException e) {
			System.out.println("Handling");
		}
		System.out.println("End");
	}

}
